# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags: [ "v**" ]

jobs:
  build:

    env:
      SOLUTION: 'src\Rhythm.Caching.Core.sln'

    runs-on: ubuntu-latest

    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Determine Version with GitVersion
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15
      with:
        useConfigFile: true
        configFilePath: ./build/GitVersion.yml

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
  
    - name: Display GitVersion SemVer
      run: |
       echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
 
    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Build
      run: dotnet build $SOLUTION --no-restore /p:version=${{ steps.gitversion.outputs.fullSemVer }}

    - name: Test
      run: dotnet test $SOLUTION --no-build --verbosity normal

    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
